import type {
  ProjectItem,
  EventItem,
  MediaItem,
  PersonItem,
  AccomplishmentItem,
  AnnouncementItem,
  UserRole,
  UserAccount,
  SiteSettings,
  AuditLogEntry,
  CollageStageSettings,
} from './types';

export const DEFAULT_ROLES: UserRole[] = [
  {
    id: 'superadmin',
    name: 'Super Admin',
    description: 'Unrestricted system authority. Manages roles, members, site settings, and all publishing pipelines.',
    permissions: ['*'],
    isSystem: true,
  },
  {
    id: 'admin',
    name: 'Admin',
    description: 'Engineering and content management authority. Manages projects, events, media, and collage layout.',
    permissions: ['admin.*'],
    isSystem: true,
  },
  {
    id: 'member',
    name: 'Member',
    description: 'Active student builder with access to internal workbench tools, bench bookings, and PR reviews.',
    permissions: [
      'profile.edit',
      'projects.view',
      'events.view',
      'benches.reserve',
    ],
    isSystem: true,
  },
];

export const DEFAULT_USERS: UserAccount[] = [];

export const DEFAULT_MEDIA: MediaItem[] = [
  {
    id: 'med_01',
    name: 'bench_alpha_night.jpg',
    url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
    category: 'COMMUNITY',
    tags: ['lab', 'night-build', 'oscilloscope'],
    size: '2.4 MB',
    dimensions: '3840x2160',
    uploadedBy: 'sneha.t@detox.build',
    uploadedAt: '2026-09-12 02:45',
    caption: 'Probing STM32 high-speed SPI bus with a 200MHz digital storage oscilloscope.',
  },
  {
    id: 'med_02',
    name: 'whiteboard_paxos.jpg',
    url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
    category: 'EVENTS',
    tags: ['paxos', 'salon', 'whiteboard'],
    size: '1.8 MB',
    dimensions: '2560x1440',
    uploadedBy: 'dev.p@detox.build',
    uploadedAt: '2026-08-15 19:30',
    caption: 'Decomposing Lamport Paxos state transitions on the seminar room blackboard.',
  },
  {
    id: 'med_03',
    name: 'pcb_stencil_reflow.jpg',
    url: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?auto=format&fit=crop&w=1200&q=80',
    category: 'PROJECTS',
    tags: ['kicad', 'smd', 'hardware'],
    size: '3.1 MB',
    dimensions: '4000x3000',
    uploadedBy: 'sneha.t@detox.build',
    uploadedAt: '2026-09-02 16:15',
    caption: 'Applying SAC305 lead-free solder paste through a 0.1mm laser-cut stainless stencil.',
  },
  {
    id: 'med_04',
    name: 'ttl_marathon_wiring.jpg',
    url: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80',
    category: 'EVENTS',
    tags: ['ttl', 'cpu', 'wire-wrap'],
    size: '2.9 MB',
    dimensions: '3024x4032',
    uploadedBy: 'root@detox.build',
    uploadedAt: '2026-08-20 11:20',
    caption: 'Point-to-point 30 AWG wire-wrapping discrete 7400-series TTL chips for the 8-bit CPU.',
  },
  {
    id: 'med_05',
    name: 'portrait_dev_p.jpg',
    url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    category: 'PEOPLE',
    tags: ['portrait', 'systems', 'kernel'],
    size: '1.2 MB',
    dimensions: '2000x2000',
    uploadedBy: 'root@detox.build',
    uploadedAt: '2026-07-10 14:00',
    caption: 'Dev P. probing APIC interrupt controller registers during x86_64 kernel boot.',
  },
  {
    id: 'med_06',
    name: 'portrait_sneha_t.jpg',
    url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
    category: 'PEOPLE',
    tags: ['portrait', 'hardware', 'pcb'],
    size: '1.4 MB',
    dimensions: '2000x2000',
    uploadedBy: 'root@detox.build',
    uploadedAt: '2026-07-10 14:15',
    caption: 'Sneha T. inspecting 0402 component placement under stereo microscope.',
  },
];

export const DEFAULT_PROJECTS: ProjectItem[] = [
  {
    id: 'detox-os',
    title: 'detox-os: Zero-Copy Ring Buffer Microkernel IPC',
    category: 'CODING',
    description: 'An educational microkernel written in C11 implementing single-producer single-consumer ring buffers with explicit acquire-release memory barriers, passing x86_64 SMP cache coherence tests.',
    visualUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    visualLabel: 'Ring-Buffer IPC Benchmark',
    visualCaption: 'Zero-copy lock-free ring buffer achieving 31.8ns IPC round-trip latency on AMD Zen 4.',
    contributors: ['Dev P.', 'Arjun M.', 'Vikram S.'],
    status: 'PUBLISHED',
    gitUrl: 'https://github.com/detox-build/detox-os',
    specs: ['C11 / x86_64', '31.8ns IPC Latency', 'Helgrind Verified', 'Ring 0 Microkernel'],
    metrics: { label: 'IPC ROUND-TRIP', value: '31.8ns' },
    createdAt: '2026-06-15',
    updatedAt: '2026-09-10',
  },
  {
    id: 'flight-core-m4',
    title: 'flight-core-m4: 4-Layer SMT Telemetry Board',
    category: 'STUDENT',
    description: 'Custom avionics board engineered in KiCad around STM32F405, featuring 50-ohm controlled-impedance differential traces, dual SPI flash logging, and an isolated 3.3V LDO power plane.',
    visualUrl: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?auto=format&fit=crop&w=1200&q=80',
    visualLabel: '4-Layer Board Assembly',
    visualCaption: 'Physical copper trace routing with differential impedance matching for high-vibration sensor telemetry.',
    contributors: ['Sneha T.', 'Rohan K.'],
    status: 'PUBLISHED',
    gitUrl: 'https://github.com/detox-build/flight-core-m4',
    specs: ['4-Layer FR-4', '50Ω Controlled Impedance', 'STM32F405 Cortex-M4', 'Hardware JTAG'],
    metrics: { label: 'SIGNAL SPEED', value: '480 Mbps USB-OTG' },
    createdAt: '2026-05-20',
    updatedAt: '2026-09-08',
  },
  {
    id: 'nano-flash-attn',
    title: 'nano-flash-attn: Minimal SRAM Tiling in CUDA',
    category: 'RESEARCH',
    description: 'Line-by-line reproduction of FlashAttention-2 in clean C/CUDA, breaking online softmax normalization across GPU shared memory tiles and eliminating HBM memory round-trips.',
    visualUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    visualLabel: 'FlashAttention-2 SRAM Kernel',
    visualCaption: 'Shared memory tiling scheme eliminating intermediate attention matrix writes to high-bandwidth memory.',
    contributors: ['Meera R.', 'Aditya N.'],
    status: 'PUBLISHED',
    gitUrl: 'https://github.com/detox-build/nano-flash-attn',
    specs: ['CUDA C++', '2.4x Speedup vs PyTorch Eager', 'Zero HBM Spills', 'FP16 Tensor Cores'],
    metrics: { label: 'SPEEDUP OVER EAGER', value: '2.4x' },
    createdAt: '2026-07-01',
    updatedAt: '2026-09-14',
  },
  {
    id: 'net-fuzz-ebpf',
    title: 'net-fuzz: Bare-Metal eBPF Socket Packet Auditor',
    category: 'OSS',
    description: 'Kernel socket monitoring framework hooking raw XDP drivers to inspect cryptographic handshake timings and audit side-channel leakage across local network interfaces.',
    visualUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    visualLabel: 'Live Side-Channel Audit',
    visualCaption: 'Nanosecond timing variance analysis over Curve25519 scalar multiplications.',
    contributors: ['Vikram S.', 'Tanya L.'],
    status: 'PUBLISHED',
    gitUrl: 'https://github.com/detox-build/net-fuzz',
    specs: ['eBPF / C', 'Raw XDP Drivers', 'Wireshark Parsing', 'Zero-Copy Ring'],
    metrics: { label: 'LINE RATE INSPECTION', value: '10 Gbps' },
    createdAt: '2026-08-05',
    updatedAt: '2026-09-15',
  },
];

export const DEFAULT_EVENTS: EventItem[] = [
  {
    id: 'evt-2026-10',
    code: 'EVT-2026-10',
    title: 'High-Speed KiCad 4-Layer Board Bring-Up & SMT Stenciling',
    category: 'WORKSHOP',
    date: 'OCTOBER 03, 2026',
    time: '14:00 - 19:00 IST',
    location: 'Hardware Lab 2 — Benches A1-A6',
    capacity: '24 Physical Benches',
    photoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
    photoLabel: 'SMT Stencil & Reflow Bench',
    photoCaption: 'Applying lead-free SAC305 solder paste through 0.1mm stainless stencils and hot air reflowing QFN packages.',
    description:
      'Taking a telemetry board schematic from netlist to physical silicon. Students route 50-ohm traces, inspect differential length matching, apply solder paste, and verify SPI loopback on real silicon.',
    deliverables: ['Assembled STM32 telemetry breakout board', 'Verified SPI loopback test', 'Open Gerber files'],
    status: 'PUBLISHED',
    isUpcoming: true,
    createdAt: '2026-09-01',
    updatedAt: '2026-09-10',
  },
  {
    id: 'evt-2026-11',
    code: 'EVT-2026-11',
    title: 'FlashAttention-2 & Memory Tiling: Line-by-Line Deconstruction',
    category: 'PAPER SALON',
    date: 'OCTOBER 09, 2026',
    time: '20:00 - 22:30 IST',
    location: 'Systems Seminar Room — Hybrid',
    capacity: 'Open to All Students',
    photoUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
    photoLabel: 'Whiteboard SRAM Tiling Derivation',
    photoCaption: 'Decomposing online softmax scaling factors across GPU SRAM chunk registers on the seminar room board.',
    description:
      'We read Tri Dao’s FlashAttention-2 paper line-by-line on the blackboard, analyzing softmax normalization across GPU SRAM chunks and writing a toy CUDA kernel.',
    deliverables: ['Annotated paper notes', 'Clean C/CUDA toy implementation', 'SRAM memory bandwidth profile'],
    status: 'PUBLISHED',
    isUpcoming: true,
    createdAt: '2026-09-05',
    updatedAt: '2026-09-12',
  },
  {
    id: 'evt-2026-12',
    code: 'EVT-2026-12',
    title: '36-Hour Unhinged Weekend Build: Homebrew 8-Bit TTL Computer',
    category: 'WEEKEND BUILD',
    date: 'OCTOBER 17-18, 2026',
    time: 'Friday 21:00 → Sunday 09:00 IST',
    location: 'DETOX Workbench Lab — 36-Hour Marathon',
    capacity: 'Physical Attendance Only',
    photoUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80',
    photoLabel: 'Wire-Wrapped 7400 TTL Matrix',
    photoCaption: 'Dense point-to-point 30 AWG wire-wrapping connecting 74LS181 ALUs, register files, and 7-segment LED bus drivers.',
    description:
      'Zero microcontrollers, zero FPGAs. Point-to-point wire-wrapping discrete 7400-series TTL logic chips on perfboards to assemble an ALU and program counter running Fibonacci numbers.',
    deliverables: ['Wire-wrapped functional 8-bit CPU', 'Instruction microcode map', 'Comprehensive war story post-mortem'],
    status: 'PUBLISHED',
    isUpcoming: true,
    createdAt: '2026-09-08',
    updatedAt: '2026-09-15',
  },
  {
    id: 'evt-2026-09',
    code: 'EVT-2026-09',
    title: 'TLS 1.3 Handshake & Curve25519 Side-Channel Attack Surface',
    category: 'SECURITY AUDIT',
    date: 'SEPTEMBER 12, 2026',
    time: 'Completed — 4.5 Hours',
    location: 'Network Security Lab',
    photoUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80',
    photoLabel: 'Wireshark Timing Analysis',
    photoCaption: 'Live Wireshark packet capture showing nanosecond timing discrepancies in non-constant-time Montgomery ladder multiplication.',
    description:
      'Captured live network traffic over an experimental campus WLAN, parsed raw Wireshark frames, and audited an educational elliptic-curve scalar multiplication implementation for non-constant-time leakage.',
    deliverables: ['14 packet capture PCAP files', 'Side-channel timing analysis graph', 'C patch fixing branch leak'],
    resources: [
      { label: 'View PCAP Analysis Log' },
      { label: 'Git Commit Patch' },
    ],
    status: 'PUBLISHED',
    isUpcoming: false,
    createdAt: '2026-08-25',
    updatedAt: '2026-09-13',
  },
  {
    id: 'evt-2026-08',
    code: 'EVT-2026-08',
    title: 'Microkernel IPC Optimization: Zero-Copy Ring Buffers in C11',
    category: 'WORKSHOP',
    date: 'AUGUST 28, 2026',
    time: 'Completed — 5 Hours',
    location: 'Systems Workshop',
    photoUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80',
    photoLabel: '8-Core Cache Concurrency Test',
    photoCaption: 'Benchmarking lock-free circular queues across AMD Zen 4 cores with acquire-release memory barriers.',
    description:
      'Students implemented Single-Producer Single-Consumer queues using acquire-release memory fences and tested thread contention on an 8-core machine, reaching 28.4 million ops/sec.',
    deliverables: ['28 student PRs merged', 'Memory barrier benchmarks', 'Valgrind Helgrind verification suites'],
    resources: [
      { label: 'C11 Benchmark Suite' },
      { label: 'Workshop Slide Notes' },
    ],
    status: 'PUBLISHED',
    isUpcoming: false,
    createdAt: '2026-08-10',
    updatedAt: '2026-08-29',
  },
];

export const DEFAULT_PEOPLE: PersonItem[] = [
  {
    id: 'per_00',
    name: 'Ekansh Gharde',
    slug: 'ekansh-g',
    roleArea: 'Technical',
    focusTag: 'AI / Research',
    oneSentence: 'Spearheads high-throughput tensor kernel research, distributed model parallel architectures, and student community infrastructure.',
    biography: 'Ekansh is an undergraduate researcher and lead admin at DETOX exploring the boundary between hardware primitives and neural execution. He organizes the systems paper salons, prototypes tensor tiling kernels, and built the core infrastructure that powers student collaboration across the community.',
    areaOfContribution: 'AI Microarchitectures, Parallel Systems & Community Direction',
    activeProject: 'nano-flash-attn / distributed kernels',
    contributedProjectIds: ['nano-flash-attn', 'detox-os'],
    participatedEventIds: ['evt-2026-08', 'evt-2026-10'],
    githubUrl: 'https://github.com/detox-build',
    email: 'ekansh@detox.build',
    socialLinks: {
      github: 'https://github.com/ekanshgharde',
      website: 'https://detox.build',
    },
    photoUrl: '/cutouts/ekansh.png',
    cutoutUrl: '/cutouts/ekansh.png',
    originalPhotoUrl: '/cutouts/ekansh.png',
    photoLabel: 'Ekansh Gharde',
    photoCaption: 'Admin & AI/Research lead profiling GPU tensor memory bandwidth.',
    stagePosition: { x: 38, y: 14 },
    stageScale: 1.28,
    stageRotation: -2.0,
    stageZIndex: 14,
    isForegroundAnchor: true,
    cutoutContour: 'paper-edge',
    collageSize: 'featured',
    aspectRatio: 'portrait',
    paletteAccent: '#38B2A2',
    tagVariant: 'teal',
    status: 'PUBLISHED',
    order: 0,
  },
  {
    id: 'per_01',
    name: 'Dev P.',
    slug: 'dev-p',
    roleArea: 'Technical',
    focusTag: 'Microkernel IPC',
    oneSentence: 'Maintains the detox-os microkernel IPC layer, writing lock-free ring buffers and x86_64 context-switching routines.',
    biography: 'Dev is a third-year undergraduate obsessed with latency at Ring 0. When he joined DETOX, he was frustrated by how much abstraction university operating system courses placed between students and bare metal. Over the last three terms, he wrote detox-os from scratch in C11, deriving acquire-release memory fences on the whiteboards and testing SMP cache coherence until the round-trip IPC latency dropped to 31.8 nanoseconds.',
    areaOfContribution: 'Kernel Runtimes, Lock-Free Concurrency, and Context Switching',
    activeProject: 'detox-os / zero-copy IPC',
    contributedProjectIds: ['detox-os'],
    participatedEventIds: ['evt-2026-08', 'evt-2026-10'],
    githubUrl: 'https://github.com/detox-build/detox-os',
    email: 'dev@detox.build',
    socialLinks: {
      twitter: 'https://twitter.com/dev_kernel',
      website: 'https://devp.build',
    },
    photoUrl: '/cutouts/dev.png',
    cutoutUrl: '/cutouts/dev.png',
    originalPhotoUrl: '/cutouts/dev.png',
    photoLabel: 'Dev P.',
    photoCaption: 'Undergraduate systems researcher probing interrupt controller registers.',
    stagePosition: { x: 23, y: 10 },
    stageScale: 1.15,
    stageRotation: 2.2,
    stageZIndex: 8,
    isForegroundAnchor: false,
    cutoutContour: 'natural',
    collageSize: 'featured',
    aspectRatio: 'portrait',
    paletteAccent: '#235347',
    tagVariant: 'darkGreen',
    status: 'PUBLISHED',
    order: 1,
  },
  {
    id: 'per_02',
    name: 'Sneha T.',
    slug: 'sneha-t',
    roleArea: 'Projects',
    focusTag: 'KiCad & Hardware',
    oneSentence: 'Designs 4-layer impedance-matched flight telemetry boards in KiCad and manages lab SMT stenciling and reflow equipment.',
    biography: 'Sneha believes hardware is not real until you smell rosin core solder. She leads the hardware bring-up group at DETOX, running multi-layer differential impedance routing in KiCad and teaching junior members how to align 0402 passive components under the stereo microscope. Her latest board, the flight-core-m4, integrates an STM32F405 with dual isolated ground planes for high-vibration avionics.',
    areaOfContribution: 'Multi-Layer PCB Layout, High-Speed Routing & SMT Stenciling',
    activeProject: 'flight-core-m4 / 4-layer PCB',
    contributedProjectIds: ['flight-core-m4'],
    participatedEventIds: ['evt-2026-10'],
    githubUrl: 'https://github.com/detox-build/flight-core-m4',
    email: 'sneha@detox.build',
    socialLinks: {
      linkedin: 'https://linkedin.com',
      website: 'https://snehat.hardware',
    },
    photoUrl: '/cutouts/sneha.png',
    cutoutUrl: '/cutouts/sneha.png',
    originalPhotoUrl: '/cutouts/sneha.png',
    photoLabel: 'Sneha T.',
    photoCaption: 'Hardware lead routing 50-ohm RF traces and managing SMT brings-up.',
    stagePosition: { x: 57, y: 12 },
    stageScale: 1.24,
    stageRotation: -1.8,
    stageZIndex: 12,
    isForegroundAnchor: true,
    cutoutContour: 'paper-edge',
    collageSize: 'lg',
    aspectRatio: 'portrait',
    paletteAccent: '#F3C3B2',
    tagVariant: 'peach',
    status: 'PUBLISHED',
    order: 2,
  },
  {
    id: 'per_03',
    name: 'Meera R.',
    slug: 'meera-r',
    roleArea: 'Research',
    focusTag: 'CUDA & Matrix Math',
    oneSentence: 'Derives and benchmarks SRAM memory tiling schemes in CUDA for minimal FlashAttention kernel implementations.',
    biography: 'Meera came to DETOX wanting to understand neural networks past high-level PyTorch APIs. She spent six weeks deconstructing the mathematical proofs of FlashAttention-2, translating online softmax normalizers directly into raw CUDA kernels that fit inside 48KB GPU shared memory tiles. Her kernels run with zero intermediate round-trips to high-bandwidth memory.',
    areaOfContribution: 'GPU Microarchitecture, CUDA Shared Memory Tiling & Tensor Math',
    activeProject: 'nano-flash-attn / SRAM tiling',
    contributedProjectIds: ['nano-flash-attn'],
    participatedEventIds: ['evt-2026-08'],
    githubUrl: 'https://github.com/detox-build/nano-flash-attn',
    email: 'meera@detox.build',
    socialLinks: {
      twitter: 'https://twitter.com/meera_tensors',
      website: 'https://meerar.xyz',
    },
    photoUrl: '/cutouts/meera.png',
    cutoutUrl: '/cutouts/meera.png',
    originalPhotoUrl: '/cutouts/meera.png',
    photoLabel: 'Meera R.',
    photoCaption: 'Student researcher profiling shared memory bank conflicts on GPU kernels.',
    stagePosition: { x: 74, y: 8 },
    stageScale: 1.14,
    stageRotation: 3.0,
    stageZIndex: 9,
    isForegroundAnchor: false,
    cutoutContour: 'natural',
    collageSize: 'lg',
    aspectRatio: 'portrait',
    paletteAccent: '#C8B6FE',
    tagVariant: 'wisteria',
    status: 'PUBLISHED',
    order: 3,
  },
  {
    id: 'per_04',
    name: 'Vikram S.',
    slug: 'vikram-s',
    roleArea: 'Operations',
    focusTag: 'eBPF & Networks',
    oneSentence: 'Audits network primitives for side-channel timing leaks and writes eBPF socket probes for bare-metal telemetry.',
    biography: 'Vikram spends his nights looking at raw Wireshark pcap traces and writing eBPF kernel probes. When the lab observed timing discrepancies in campus cryptographic benchmarks, Vikram isolated the non-constant-time Montgomery ladder branches down to CPU cycle counts, publishing an open patch that fixed the side-channel vulnerability.',
    areaOfContribution: 'Network Verification, Cryptographic Side-Channels & eBPF Telemetry',
    activeProject: 'net-fuzz / Curve25519 audit',
    contributedProjectIds: ['detox-os'],
    participatedEventIds: ['evt-2026-09'],
    githubUrl: 'https://github.com/detox-build/net-fuzz',
    email: 'vikram@detox.build',
    socialLinks: {
      twitter: 'https://twitter.com/vikram_sec',
    },
    photoUrl: '/cutouts/vikram.png',
    cutoutUrl: '/cutouts/vikram.png',
    originalPhotoUrl: '/cutouts/vikram.png',
    photoLabel: 'Vikram S.',
    photoCaption: 'Security systems builder auditing cryptographic latency variance.',
    stagePosition: { x: 8, y: 12 },
    stageScale: 1.08,
    stageRotation: -3.2,
    stageZIndex: 6,
    isForegroundAnchor: false,
    cutoutContour: 'natural',
    collageSize: 'md',
    aspectRatio: 'portrait',
    paletteAccent: '#99CDD8',
    tagVariant: 'blue',
    status: 'PUBLISHED',
    order: 4,
  },
  {
    id: 'per_05',
    name: 'Arjun M.',
    slug: 'arjun-m',
    roleArea: 'Open Source',
    focusTag: 'LLVM Toolchains',
    oneSentence: 'Builds deterministic build pipelines, continuous benchmarking harnesses, and developer CLI tools for the community.',
    biography: 'Arjun is the backbone of the DETOX open-source infrastructure. He ensures every student repository builds with zero warnings, provides deterministic cross-compilers for ARM and RISC-V targets, and maintains the CI regression suite that catches performance regressions down to the nanosecond.',
    areaOfContribution: 'Compilers, CI/CD Benchmarking & Developer Toolchains',
    activeProject: 'toolchain / regression harness',
    contributedProjectIds: ['detox-os'],
    participatedEventIds: ['evt-2026-08'],
    githubUrl: 'https://github.com/detox-build',
    email: 'arjun@detox.build',
    socialLinks: {
      website: 'https://arjunm.dev',
    },
    photoUrl: '/cutouts/arjun.png',
    cutoutUrl: '/cutouts/arjun.png',
    originalPhotoUrl: '/cutouts/arjun.png',
    photoLabel: 'Arjun M.',
    photoCaption: 'Compilers student checking LLVM IR lowering passes and zero-cost abstractions.',
    stagePosition: { x: 88, y: 15 },
    stageScale: 1.12,
    stageRotation: -2.0,
    stageZIndex: 10,
    isForegroundAnchor: false,
    cutoutContour: 'natural',
    collageSize: 'md',
    aspectRatio: 'portrait',
    paletteAccent: '#ECA6B7',
    tagVariant: 'dustyRose',
    status: 'PUBLISHED',
    order: 5,
  },
  {
    id: 'per_06',
    name: 'Tanya L.',
    slug: 'tanya-l',
    roleArea: 'Community',
    focusTag: 'Lab Operations',
    oneSentence: 'Procures electronic components, maintains lab test equipment, and coordinates 36-hour sprint logistics.',
    biography: 'Tanya keeps the physical engineering lab alive. From sourcing reels of 0.1uF bypass capacitors and 4-layer FR4 boards to calibrating four-channel digital storage oscilloscopes and keeping espresso stocked for 36-hour sprints, Tanya ensures students have every physical tool needed to build without bureaucratic friction.',
    areaOfContribution: 'Physical Lab Operations, Inventory Sourcing & Equipment Calibration',
    activeProject: 'lab-inventory / equipment calibration',
    contributedProjectIds: ['flight-core-m4'],
    participatedEventIds: ['evt-2026-10'],
    githubUrl: 'https://github.com/detox-build',
    email: 'tanya@detox.build',
    socialLinks: {
      linkedin: 'https://linkedin.com',
    },
    photoUrl: '/cutouts/tanya.png',
    cutoutUrl: '/cutouts/tanya.png',
    originalPhotoUrl: '/cutouts/tanya.png',
    photoLabel: 'Tanya L.',
    photoCaption: 'Lab equipment coordinator calibrating 4-channel digital storage oscilloscopes.',
    stagePosition: { x: 48, y: 2 },
    stageScale: 1.06,
    stageRotation: 2.5,
    stageZIndex: 6,
    isForegroundAnchor: false,
    cutoutContour: 'natural',
    collageSize: 'featured',
    aspectRatio: 'portrait',
    paletteAccent: '#E8BBCF',
    tagVariant: 'orchid',
    status: 'PUBLISHED',
    order: 6,
  },
  {
    id: 'per_07',
    name: 'Rohan K.',
    slug: 'rohan-k',
    roleArea: 'Projects',
    focusTag: 'FPGA & RISC-V',
    oneSentence: 'Synthesizes pipelined RV32I cores on Xilinx FPGAs and verifies branch prediction logic with SystemVerilog testbenches.',
    biography: 'Rohan is fascinated by computer architecture at the gate level. He co-led the wire-wrapped 8-bit TTL CPU bring-up and writes custom RISC-V softcores targeting Artix-7 FPGAs. He spends weekends analyzing waveform traces in GTKWave and calculating setup and hold timing margins for high-frequency peripherals.',
    areaOfContribution: 'SystemVerilog Synthesis, RISC-V Microarchitecture & Logic Analyzers',
    activeProject: 'rv32-core / FPGA synthesis',
    contributedProjectIds: ['flight-core-m4'],
    participatedEventIds: ['evt-2026-10'],
    githubUrl: 'https://github.com/detox-build',
    email: 'rohan@detox.build',
    socialLinks: {
      github: 'https://github.com/rohan-fpga',
    },
    photoUrl: '/cutouts/rohan.png',
    cutoutUrl: '/cutouts/rohan.png',
    originalPhotoUrl: '/cutouts/rohan.png',
    photoLabel: 'Rohan K.',
    photoCaption: 'FPGA designer verifying 5-stage RISC-V pipeline hazard detection.',
    stagePosition: { x: 31, y: 3 },
    stageScale: 1.04,
    stageRotation: -1.5,
    stageZIndex: 5,
    isForegroundAnchor: false,
    cutoutContour: 'natural',
    collageSize: 'md',
    aspectRatio: 'portrait',
    paletteAccent: '#6B9080',
    tagVariant: 'laurel',
    status: 'PUBLISHED',
    order: 7,
  },
  {
    id: 'per_08',
    name: 'Aditya N.',
    slug: 'aditya-n',
    roleArea: 'Research',
    focusTag: 'Memory Allocators',
    oneSentence: 'Profiles cache line contention in multi-threaded slab allocators and explores custom WebAssembly JIT optimizations.',
    biography: 'Aditya studies memory hierarchies and allocator ergonomics. Working closely with Meera and Dev, he built custom slab allocators with per-thread arenas that eliminate cross-core lock contention. His benchmarks run in continuous integration on native Linux and WebAssembly runtimes.',
    areaOfContribution: 'Memory Allocators, Multi-Threading Contention & JIT Compilation',
    activeProject: 'slab-alloc / lock-free arenas',
    contributedProjectIds: ['nano-flash-attn', 'detox-os'],
    participatedEventIds: ['evt-2026-08'],
    githubUrl: 'https://github.com/detox-build',
    email: 'aditya@detox.build',
    socialLinks: {
      twitter: 'https://twitter.com/aditya_alloc',
    },
    photoUrl: '/cutouts/aditya.png',
    cutoutUrl: '/cutouts/aditya.png',
    originalPhotoUrl: '/cutouts/aditya.png',
    photoLabel: 'Aditya N.',
    photoCaption: 'Systems researcher analyzing cache line invalidation patterns.',
    stagePosition: { x: 67, y: 1 },
    stageScale: 1.02,
    stageRotation: 1.6,
    stageZIndex: 4,
    isForegroundAnchor: false,
    cutoutContour: 'natural',
    collageSize: 'sm',
    aspectRatio: 'portrait',
    paletteAccent: '#FFB7C3',
    tagVariant: 'coral',
    status: 'PUBLISHED',
    order: 8,
  },
];

export const DEFAULT_ACCOMPLISHMENTS: AccomplishmentItem[] = [
  {
    id: 'acc_01',
    title: 'Completed 36-Hour Discrete 7400 TTL 8-Bit Computer Bring-Up',
    date: 'AUGUST 2026',
    category: 'MILESTONE',
    description: 'Wire-wrapped 48 discrete logic ICs point-to-point without microcontrollers, successfully executing Fibonacci computation on dual 7-segment LED bus monitors.',
    impact: 'Hardware verified in front of 35 student witnesses; schematics published open-hardware.',
    status: 'PUBLISHED',
  },
  {
    id: 'acc_02',
    title: 'detox-os Microkernel Passed 10 Million Iteration Concurrency Stress Test',
    date: 'JULY 2026',
    category: 'MILESTONE',
    description: 'Single-producer single-consumer lock-free IPC queue completed multi-threaded stress tests on 16 AMD Zen 4 threads with 0 memory corruption bugs under Valgrind Helgrind.',
    impact: 'Published reproducible benchmark harness reaching 31.8ns latency.',
    status: 'PUBLISHED',
  },
  {
    id: 'acc_03',
    title: 'FlashAttention-2 Minimal Kernel Verified Against PyTorch Reference',
    date: 'JUNE 2026',
    category: 'SELECTION',
    description: 'Student-authored CUDA kernel matched PyTorch attention outputs within 1e-4 float tolerance while cutting peak SRAM requirements by 60%.',
    impact: 'Used as core teaching curriculum in the systems paper salon.',
    status: 'PUBLISHED',
  },
];

export const DEFAULT_ANNOUNCEMENTS: AnnouncementItem[] = [
  {
    id: 'ann_01',
    title: 'Lab Benches A1-A6 Prepped for KiCad SMT Stenciling Workshop',
    content: 'Lead-free SAC305 paste and hot-air reflow wands have been calibrated. Please ensure KiCad 8.0 Gerber netlists are generated before arrival.',
    type: 'RELEASE',
    date: '2026-09-16',
    active: true,
    status: 'PUBLISHED',
  },
];

export const DEFAULT_SETTINGS: SiteSettings = {
  siteTitle: 'DETOX',
  tagline: 'A student community built around learning, building and contributing.',
  memberCountText: '800+ Active Builders',
  contactEmail: 'collective@detox.build',
  allowPublicSubmissions: true,
  maintenanceMode: false,
};

export const DEFAULT_COLLAGE_SETTINGS: CollageStageSettings = {
  title: 'Minds Behind DETOX.',
  categoryTag: 'Active Student Collective',
  leadText:
    'No executives, directors, or marketing figureheads. DETOX is conceived, engineered, and maintained entirely by undergraduate students who spend their evenings designing microkernels, routing PCBs, and running 36-hour weekend marathons.',
  statusText: 'Cohort 2026 • 9 Active Builders',
  bgType: 'gradient',
  bgColor: '#235347',
  pattern: 'grid',
  hoverBehavior: {
    focusScale: 'standard',
    recession: 'medium',
    blur: 'none',
    lift: 'medium',
    speed: 'normal',
    labelStyle: 'editorial',
  },
  decorativeElements: [
    {
      id: 'dec_01',
      type: 'stamp',
      x: 88,
      y: 84,
      scale: 1,
      rotation: 8,
      text: 'DETOX // 2026',
      color: '#38B2A2',
    },
    {
      id: 'dec_02',
      type: 'tape',
      x: 12,
      y: 88,
      scale: 1,
      rotation: -6,
      text: 'LAB BENCH // LIVE',
      color: '#FDE8D3',
    },
    {
      id: 'dec_03',
      type: 'color-chip',
      x: 50,
      y: 92,
      scale: 0.9,
      rotation: 0,
      text: 'SYSTEMS COLLECTIVE',
      color: '#235347',
    },
  ],
};

export const DEFAULT_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud_01',
    timestamp: '2026-09-16 18:40:12',
    actorId: 'usr_root',
    actorName: 'Root Operator',
    actorRole: 'Super Admin',
    action: 'PUBLISH',
    targetType: 'EVENT',
    targetId: 'evt-2026-10',
    details: 'Published KiCad 4-Layer Board Bring-Up Workshop with 24 physical bench capacity.',
  },
  {
    id: 'aud_02',
    timestamp: '2026-09-15 22:15:00',
    actorId: 'usr_dev',
    actorName: 'Dev P.',
    actorRole: 'Projects Admin',
    action: 'UPDATE',
    targetType: 'PROJECT',
    targetId: 'detox-os',
    details: 'Updated detox-os benchmark telemetry to 31.8ns IPC round-trip.',
  },
  {
    id: 'aud_03',
    timestamp: '2026-09-14 14:10:05',
    actorId: 'usr_sneha',
    actorName: 'Sneha T.',
    actorRole: 'Events Admin',
    action: 'CREATE',
    targetType: 'MEDIA',
    targetId: 'med_01',
    details: 'Uploaded bench_alpha_night.jpg to Media Library in category COMMUNITY.',
  },
];
