-- ============================================================================
-- DETOX Platform V2 — Seed Data Migration
-- Seed: supabase/seed.sql
-- ============================================================================

-- 1. COLLAGE STAGE SETTINGS
INSERT INTO public.collage_settings (
    id, title, category_tag, lead_text, status_text, bg_type, bg_color, pattern, hover_behavior, decorative_elements
) VALUES (
    'global',
    'Minds Behind DETOX',
    'STUDENT ENGINEERING CORPS',
    'The minds behind DETOX are undergraduate builders, kernel tinkerers, PCB designers, and compiler hackers working together in our student laboratory.',
    'STATUS: 09 ACTIVE PROFILES DEPLOYED',
    'paper',
    '#111215',
    'grid',
    '{
        "focusScale": "prominent",
        "recession": "medium",
        "blur": "subtle",
        "lift": "high",
        "speed": "normal",
        "labelStyle": "editorial"
    }'::jsonb,
    '[
        {
            "id": "dec_01",
            "type": "stamp",
            "x": 12,
            "y": 6,
            "scale": 1.0,
            "rotation": -8,
            "text": "VERIFIED BUILDERS // 2026",
            "color": "#235347"
        },
        {
            "id": "dec_02",
            "type": "color-chip",
            "x": 84,
            "y": 8,
            "scale": 1.1,
            "rotation": 6,
            "text": "LAB 2 HW SMT",
            "color": "#38B2A2"
        }
    ]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category_tag = EXCLUDED.category_tag,
    lead_text = EXCLUDED.lead_text,
    status_text = EXCLUDED.status_text,
    bg_type = EXCLUDED.bg_type,
    bg_color = EXCLUDED.bg_color,
    pattern = EXCLUDED.pattern,
    hover_behavior = EXCLUDED.hover_behavior,
    decorative_elements = EXCLUDED.decorative_elements;

-- 2. PROJECTS
INSERT INTO public.projects (
    id, title, category, description, visual_url, visual_label, visual_caption, contributors, status, git_url, specs, metrics
) VALUES
(
    'detox-os',
    'detox-os: Zero-Copy Ring Buffer Microkernel IPC',
    'CODING',
    'An educational microkernel written in C11 implementing single-producer single-consumer ring buffers with explicit acquire-release memory barriers, passing x86_64 SMP cache coherence tests.',
    'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    'Ring-Buffer IPC Benchmark',
    'Zero-copy lock-free ring buffer achieving 31.8ns IPC round-trip latency on AMD Zen 4.',
    ARRAY['Dev P.', 'Arjun M.', 'Vikram S.'],
    'PUBLISHED',
    'https://github.com/detox-build/detox-os',
    ARRAY['C11 / x86_64', '31.8ns IPC Latency', 'Helgrind Verified', 'Ring 0 Microkernel'],
    '{"label": "IPC ROUND-TRIP", "value": "31.8ns"}'::jsonb
),
(
    'flight-core-m4',
    'flight-core-m4: 4-Layer SMT Telemetry Board',
    'STUDENT',
    'Custom avionics board engineered in KiCad around STM32F405, featuring 50-ohm controlled-impedance differential traces, dual SPI flash logging, and an isolated 3.3V LDO power plane.',
    'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?auto=format&fit=crop&w=1200&q=80',
    '4-Layer Board Assembly',
    'Physical copper trace routing with differential impedance matching for high-vibration sensor telemetry.',
    ARRAY['Sneha T.', 'Rohan K.'],
    'PUBLISHED',
    'https://github.com/detox-build/flight-core-m4',
    ARRAY['4-Layer FR-4', '50Ω Controlled Impedance', 'STM32F405 Cortex-M4', 'Hardware JTAG'],
    '{"label": "SIGNAL SPEED", "value": "480 Mbps USB-OTG"}'::jsonb
),
(
    'nano-flash-attn',
    'nano-flash-attn: Minimal SRAM Tiling in CUDA',
    'RESEARCH',
    'Line-by-line reproduction of FlashAttention-2 in clean C/CUDA, breaking online softmax normalization across GPU shared memory tiles and eliminating HBM memory round-trips.',
    'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    'FlashAttention-2 SRAM Kernel',
    'Shared memory tiling scheme eliminating intermediate attention matrix writes to high-bandwidth memory.',
    ARRAY['Meera R.', 'Aditya N.'],
    'PUBLISHED',
    'https://github.com/detox-build/nano-flash-attn',
    ARRAY['CUDA C++', '2.4x Speedup vs PyTorch Eager', 'Zero HBM Spills', 'FP16 Tensor Cores'],
    '{"label": "BANDWIDTH SAVINGS", "value": "78% vs Eager"}'::jsonb
),
(
    'robotic-manipulator-v1',
    'robotic-manipulator-v1: 6-DOF Inverse Kinematics',
    'OSS',
    'Real-time trajectory planning engine running on ARM Cortex-M7 with sub-millimeter repeatable inverse kinematics for small-scale robotic arms.',
    'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1200&q=80',
    '6-DOF Arm Kinematics',
    'Real-time Jacobian matrix solver running on bare-metal microcontroller.',
    ARRAY['Dev P.', 'Tanya L.'],
    'PUBLISHED',
    'https://github.com/detox-build/robotic-manipulator-v1',
    ARRAY['Rust / ARM M7', 'Sub-millimeter Repeatability', 'Jacobian Solver'],
    '{"label": "CYCLE JITTER", "value": "< 12 microseconds"}'::jsonb
),
(
    'ebpf-firewall-jit',
    'ebpf-firewall-jit: Line-Rate XDP Packet Filter',
    'CODING',
    'Kernel-space eBPF program filtering DDOS flood traffic at physical line rate (10 Gbps) before sk_buff memory allocation.',
    'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    'XDP Driver Packet Filter',
    'Sub-microsecond packet classification executed directly in network card ring buffer.',
    ARRAY['Vikram S.', 'Dev P.'],
    'PUBLISHED',
    'https://github.com/detox-build/ebpf-firewall-jit',
    ARRAY['C / eBPF / XDP', '14.8M pps Throughput', 'Zero Kernel Allocation'],
    '{"label": "PACKET LOSS", "value": "0.00% at 10Gbps"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    visual_url = EXCLUDED.visual_url,
    visual_label = EXCLUDED.visual_label,
    visual_caption = EXCLUDED.visual_caption,
    contributors = EXCLUDED.contributors,
    status = EXCLUDED.status,
    git_url = EXCLUDED.git_url,
    specs = EXCLUDED.specs,
    metrics = EXCLUDED.metrics;

-- 3. EVENTS
INSERT INTO public.events (
    id, code, title, category, date, time, location, capacity, description, photo_url, photo_label, photo_caption, deliverables, resources, status, is_upcoming
) VALUES
(
    'evt-2026-08',
    'DTX-WS-08',
    'Paper Salon: FlashAttention-2 Block Tiling',
    'PAPER SALON',
    '2026-09-24',
    '18:30 - 21:00 IST',
    'DETOX Lab Room 204 & Streaming',
    '30 Seats Physical',
    'Deconstructing Dao et al. Line-by-line breakdown of online softmax normalization and GPU shared memory bank conflicts.',
    'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
    'Paper Salon Blackboard Session',
    'Deriving GPU shared memory tiling arithmetic and online softmax normalizers.',
    ARRAY['Annotated PDF Margins', 'Toy CUDA shared memory kernel', 'Roofline model chart'],
    '[{"label": "ArXiv Paper", "url": "https://arxiv.org/abs/2307.08691"}, {"label": "CUDA Repo", "url": "https://github.com/detox-build"}]'::jsonb,
    'PUBLISHED',
    true
),
(
    'evt-2026-09',
    'DTX-WB-09',
    'Weekend Build: Discrete 7400 TTL 8-Bit CPU',
    'WEEKEND BUILD',
    '2026-10-04',
    '10:00 - 22:00 IST',
    'Electronics Lab Bench B1-B6',
    '16 Builders (4 Teams)',
    '12-hour sprint wire-wrapping an 8-bit accumulator ALU with discrete 7400 NAND chips, driving an LED instruction pointer.',
    'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80',
    '7400-Series Breadboard Assembly',
    'Wiring 74LS181 ALUs with discrete flip-flops and zero microcontrollers.',
    ARRAY['Running 8-bit Fibonacci sequence', 'KiCad wire-wrap netlist', 'Logic analyzer traces'],
    '[{"label": "ALU Schematic", "url": "https://github.com/detox-build"}]'::jsonb,
    'PUBLISHED',
    true
),
(
    'evt-2026-10',
    'DTX-SEC-10',
    'Security Audit: Cache Side-Channels on x86_64',
    'SECURITY AUDIT',
    '2026-10-18',
    '14:00 - 18:00 IST',
    'Systems Lab 3',
    '25 Seats',
    'Hands-on vulnerability reproduction: Flush+Reload cache timing attacks, isolating secret AES keys through cycle-accurate RDTSC measurement.',
    'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    'L1/L3 Cache Timing Analysis',
    'Isolating non-constant-time memory lookups using cycle-accurate CPU performance counters.',
    ARRAY['Working Flush+Reload exploit harness', 'Mitigation patch submission guide'],
    '[{"label": "Exploit Harness Code", "url": "https://github.com/detox-build"}]'::jsonb,
    'PUBLISHED',
    true
),
(
    'game-building-hackathon-2026',
    'DTX-GAME-2026',
    'DETOX Game Building Hackathon 2026',
    'HACKATHON',
    '2026-10-26',
    '48-Hour Hybrid Build Sprint',
    'DETOX Hardware Lab & Online Discord',
    '64 Builders / 18 Teams',
    'A 48-hour student game development marathon focused on bespoke graphics engines, raymarched shaders, fixed-point deterministic physics, and mechanical arcade controls.',
    'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
    'Game Physics & Custom Engine Bring-Up',
    'Students assembling custom collision pipelines, GLSL shaders, and WASM bindings with zero corporate engine bloat.',
    ARRAY['Playable web or binary game build', 'Public Git repository', 'Engineering post-mortem write-up'],
    '[{"label": "Submissions Gallery", "url": "/events/game-building-hackathon-2026/submissions"}]'::jsonb,
    'PUBLISHED',
    false
)
ON CONFLICT (id) DO UPDATE SET
    code = EXCLUDED.code,
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    date = EXCLUDED.date,
    time = EXCLUDED.time,
    location = EXCLUDED.location,
    capacity = EXCLUDED.capacity,
    description = EXCLUDED.description,
    photo_url = EXCLUDED.photo_url,
    photo_label = EXCLUDED.photo_label,
    photo_caption = EXCLUDED.photo_caption,
    deliverables = EXCLUDED.deliverables,
    resources = EXCLUDED.resources,
    status = EXCLUDED.status,
    is_upcoming = EXCLUDED.is_upcoming;

-- 4. PEOPLE / MINDS BEHIND DETOX
INSERT INTO public.people (
    id, name, slug, role_area, focus_tag, one_sentence, biography, area_of_contribution, active_project, contributed_project_ids, participated_event_ids, github_url, email, social_links, photo_url, cutout_url, original_photo_url, photo_label, photo_caption, stage_position, stage_scale, stage_rotation, stage_z_index, is_foreground_anchor, cutout_contour, collage_size, aspect_ratio, palette_accent, tag_variant, status, display_order
) VALUES
(
    'per_00',
    'Ekansh Gharde',
    'ekansh-gharde',
    'Technical',
    'Founder & Research Lead',
    'Leads the core engineering group at DETOX, architecting distributed systems benchmarks and high-throughput GPU kernel pipelines.',
    'Ekansh founded DETOX to create a no-fluff sanctuary where engineering students could write bare-metal code and fabricate custom electronics without academic red tape.',
    'Founding Architecture, Microarchitecture Research, GPU Kernel Optimization',
    'DETOX Platform Core / Kernel Benchmarks',
    ARRAY['detox-os', 'nano-flash-attn'],
    ARRAY['evt-2026-08', 'evt-2026-09'],
    'https://github.com/EkanshGharde',
    'ekansh@detox.build',
    '{"website": "https://github.com/EkanshGharde", "linkedin": "https://linkedin.com/in/ekansh-gharde"}'::jsonb,
    '/cutouts/ekansh.png',
    '/cutouts/ekansh.png',
    '/cutouts/ekansh.png',
    'Ekansh Gharde',
    'Founder & AI/Research lead profiling GPU tensor memory bandwidth.',
    '{"x": 38, "y": 14}'::jsonb,
    1.28,
    -2.0,
    14,
    true,
    'paper-edge',
    'featured',
    'portrait',
    '#38B2A2',
    'teal',
    'PUBLISHED',
    0
),
(
    'per_01',
    'Dev P.',
    'dev-p',
    'Technical',
    'Microkernel IPC',
    'Maintains the detox-os microkernel IPC layer, writing lock-free ring buffers and x86_64 context-switching routines.',
    'Dev is a third-year undergraduate obsessed with latency at Ring 0. Over the last three terms, he wrote detox-os from scratch in C11, deriving acquire-release memory fences on the whiteboards.',
    'Kernel Runtimes, Lock-Free Concurrency, and Context Switching',
    'detox-os / zero-copy IPC',
    ARRAY['detox-os'],
    ARRAY['evt-2026-08', 'evt-2026-10'],
    'https://github.com/detox-build/detox-os',
    'dev@detox.build',
    '{"twitter": "https://twitter.com/dev_kernel", "website": "https://devp.build"}'::jsonb,
    '/cutouts/dev.png',
    '/cutouts/dev.png',
    '/cutouts/dev.png',
    'Dev P.',
    'Undergraduate systems researcher probing interrupt controller registers.',
    '{"x": 23, "y": 10}'::jsonb,
    1.15,
    2.2,
    8,
    false,
    'natural',
    'featured',
    'portrait',
    '#235347',
    'darkGreen',
    'PUBLISHED',
    1
),
(
    'per_02',
    'Sneha T.',
    'sneha-t',
    'Projects',
    'KiCad & Hardware',
    'Designs 4-layer impedance-matched flight telemetry boards in KiCad and manages lab SMT stenciling and reflow equipment.',
    'Sneha leads the hardware bring-up group at DETOX, running multi-layer differential impedance routing in KiCad and teaching junior members how to align 0402 passive components.',
    'Multi-Layer PCB Layout, High-Speed Routing & SMT Stenciling',
    'flight-core-m4 / 4-layer PCB',
    ARRAY['flight-core-m4'],
    ARRAY['evt-2026-10'],
    'https://github.com/detox-build/flight-core-m4',
    'sneha@detox.build',
    '{"linkedin": "https://linkedin.com", "website": "https://snehat.hardware"}'::jsonb,
    '/cutouts/sneha.png',
    '/cutouts/sneha.png',
    '/cutouts/sneha.png',
    'Sneha T.',
    'Hardware lead routing 50-ohm RF traces and managing SMT brings-up.',
    '{"x": 57, "y": 12}'::jsonb,
    1.24,
    -1.8,
    12,
    true,
    'paper-edge',
    'lg',
    'portrait',
    '#F3C3B2',
    'peach',
    'PUBLISHED',
    2
),
(
    'per_03',
    'Meera R.',
    'meera-r',
    'Research',
    'CUDA & Matrix Math',
    'Derives and benchmarks SRAM memory tiling schemes in CUDA for minimal FlashAttention kernel implementations.',
    'Meera spent six weeks deconstructing the mathematical proofs of FlashAttention-2, translating online softmax normalizers directly into raw CUDA kernels.',
    'GPU Microarchitecture, CUDA Shared Memory Tiling & Tensor Math',
    'nano-flash-attn / SRAM tiling',
    ARRAY['nano-flash-attn'],
    ARRAY['evt-2026-08'],
    'https://github.com/detox-build/nano-flash-attn',
    'meera@detox.build',
    '{"twitter": "https://twitter.com/meera_tensors", "website": "https://meerar.xyz"}'::jsonb,
    '/cutouts/meera.png',
    '/cutouts/meera.png',
    '/cutouts/meera.png',
    'Meera R.',
    'Student researcher profiling shared memory bank conflicts on GPU kernels.',
    '{"x": 74, "y": 8}'::jsonb,
    1.14,
    3.0,
    9,
    false,
    'natural',
    'lg',
    'portrait',
    '#C8B6FE',
    'wisteria',
    'PUBLISHED',
    3
),
(
    'per_04',
    'Vikram S.',
    'vikram-s',
    'Operations',
    'eBPF & Networks',
    'Audits network primitives for side-channel timing leaks and writes eBPF socket probes for bare-metal telemetry.',
    'Vikram spends his nights looking at raw Wireshark pcap traces and writing eBPF kernel probes for side-channel analysis.',
    'Network Verification, Cryptographic Side-Channels & eBPF Telemetry',
    'net-fuzz / Curve25519 audit',
    ARRAY['detox-os'],
    ARRAY['evt-2026-09'],
    'https://github.com/detox-build/net-fuzz',
    'vikram@detox.build',
    '{"twitter": "https://twitter.com/vikram_sec"}'::jsonb,
    '/cutouts/vikram.png',
    '/cutouts/vikram.png',
    '/cutouts/vikram.png',
    'Vikram S.',
    'Security systems builder auditing cryptographic latency variance.',
    '{"x": 8, "y": 12}'::jsonb,
    1.08,
    -3.2,
    6,
    false,
    'natural',
    'md',
    'portrait',
    '#99CDD8',
    'blue',
    'PUBLISHED',
    4
),
(
    'per_05',
    'Arjun M.',
    'arjun-m',
    'Open Source',
    'LLVM Toolchains',
    'Builds deterministic build pipelines, continuous benchmarking harnesses, and developer CLI tools for the community.',
    'Arjun is the backbone of the DETOX open-source infrastructure, maintaining deterministic cross-compilers for ARM and RISC-V targets.',
    'Compilers, CI/CD Benchmarking & Developer Toolchains',
    'toolchain / regression harness',
    ARRAY['detox-os'],
    ARRAY['evt-2026-08'],
    'https://github.com/detox-build',
    'arjun@detox.build',
    '{"website": "https://arjunm.dev"}'::jsonb,
    '/cutouts/arjun.png',
    '/cutouts/arjun.png',
    '/cutouts/arjun.png',
    'Arjun M.',
    'Compilers student checking LLVM IR lowering passes and zero-cost abstractions.',
    '{"x": 88, "y": 15}'::jsonb,
    1.12,
    -2.0,
    10,
    false,
    'natural',
    'md',
    'portrait',
    '#ECA6B7',
    'dustyRose',
    'PUBLISHED',
    5
),
(
    'per_06',
    'Tanya L.',
    'tanya-l',
    'Design',
    'Physical Artifacts',
    'Fabrics mechanical chassis, acrylic laser cut enclosures, and ergonomic lab workbench layouts.',
    'Tanya merges industrial design with electrical engineering to produce functional, robust lab hardware enclosures.',
    'Mechanical Fabrication, Rapid Prototyping, Ergonomic Workbench Topology',
    'bench-enclosure / modular rack',
    ARRAY['robotic-manipulator-v1'],
    ARRAY['evt-2026-09'],
    'https://github.com/detox-build',
    'tanya@detox.build',
    '{"website": "https://tanyal.design"}'::jsonb,
    '/cutouts/tanya.png',
    '/cutouts/tanya.png',
    '/cutouts/tanya.png',
    'Tanya L.',
    'Industrial designer milling acrylic lab bench test fixtures.',
    '{"x": 48, "y": 42}'::jsonb,
    1.10,
    1.5,
    7,
    false,
    'natural',
    'md',
    'portrait',
    '#FFB7C3',
    'rose',
    'PUBLISHED',
    6
),
(
    'per_07',
    'Rohan K.',
    'rohan-k',
    'Events',
    'FPGA Bring-up',
    'Synthesizes RISC-V soft cores on Lattice ECP5 FPGAs and leads weekend hardware hackathons.',
    'Rohan translates Verilog RTL into bitstreams and teaches undergraduate students how to write digital logic circuits.',
    'Verilog RTL, FPGA Synthesis & Hardware Hackathon Logistics',
    'fpga-core / Lattice ECP5',
    ARRAY['flight-core-m4'],
    ARRAY['evt-2026-09', 'evt-2026-10'],
    'https://github.com/detox-build',
    'rohan@detox.build',
    '{"twitter": "https://twitter.com/rohan_fpga"}'::jsonb,
    '/cutouts/rohan.png',
    '/cutouts/rohan.png',
    '/cutouts/rohan.png',
    'Rohan K.',
    'FPGA researcher probing high-speed JTAG boundary scan pins.',
    '{"x": 16, "y": 38}'::jsonb,
    1.08,
    -1.5,
    5,
    false,
    'natural',
    'sm',
    'portrait',
    '#C8B6FE',
    'wisteria',
    'PUBLISHED',
    7
),
(
    'per_08',
    'Aditya N.',
    'aditya-n',
    'Community',
    'Distributed Systems',
    'Formalizes Raft state machines in TLA+ and manages the DETOX peer reading group.',
    'Aditya believes distributed systems correctness must be mathematically proven before being implemented in code.',
    'Formal Verification, TLA+ Specs & Paper Salon Coordination',
    'raft-tla / formal consensus',
    ARRAY['nano-flash-attn'],
    ARRAY['evt-2026-08'],
    'https://github.com/detox-build',
    'aditya@detox.build',
    '{"website": "https://adityan.systems"}'::jsonb,
    '/cutouts/aditya.png',
    '/cutouts/aditya.png',
    '/cutouts/aditya.png',
    'Aditya N.',
    'Formal verification student verifying invariant assertions in TLA+.',
    '{"x": 78, "y": 40}'::jsonb,
    1.06,
    2.8,
    4,
    false,
    'natural',
    'sm',
    'portrait',
    '#99CDD8',
    'blue',
    'PUBLISHED',
    8
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    role_area = EXCLUDED.role_area,
    focus_tag = EXCLUDED.focus_tag,
    one_sentence = EXCLUDED.one_sentence,
    biography = EXCLUDED.biography,
    area_of_contribution = EXCLUDED.area_of_contribution,
    active_project = EXCLUDED.active_project,
    contributed_project_ids = EXCLUDED.contributed_project_ids,
    participated_event_ids = EXCLUDED.participated_event_ids,
    github_url = EXCLUDED.github_url,
    email = EXCLUDED.email,
    social_links = EXCLUDED.social_links,
    photo_url = EXCLUDED.photo_url,
    cutout_url = EXCLUDED.cutout_url,
    original_photo_url = EXCLUDED.original_photo_url,
    photo_label = EXCLUDED.photo_label,
    photo_caption = EXCLUDED.photo_caption,
    stage_position = EXCLUDED.stage_position,
    stage_scale = EXCLUDED.stage_scale,
    stage_rotation = EXCLUDED.stage_rotation,
    stage_z_index = EXCLUDED.stage_z_index,
    is_foreground_anchor = EXCLUDED.is_foreground_anchor,
    cutout_contour = EXCLUDED.cutout_contour,
    collage_size = EXCLUDED.collage_size,
    aspect_ratio = EXCLUDED.aspect_ratio,
    palette_accent = EXCLUDED.palette_accent,
    tag_variant = EXCLUDED.tag_variant,
    status = EXCLUDED.status,
    display_order = EXCLUDED.display_order;

-- 5. ACCOMPLISHMENTS
INSERT INTO public.accomplishments (
    id, title, date, category, description, impact, verified_link, status
) VALUES
(
    'acc_01',
    'National Open-Source Microkernel Commendation',
    '2026-08-14',
    'AWARD',
    'detox-os was recognized by the Systems Architecture Foundation for exceptional low-latency zero-copy IPC design in an undergraduate project.',
    'Top 0.1% latency benchmark nationwide',
    'https://github.com/detox-build/detox-os',
    'PUBLISHED'
),
(
    'acc_02',
    'First Place — Inter-University Hardware SMT Sprint',
    '2026-07-22',
    'HACKATHON',
    'The DETOX avionics team designed, routed, stenciled, and reflowed the flight-core-m4 PCB in under 36 hours with zero trace bridges.',
    '36-hour rapid hardware turnaround',
    'https://github.com/detox-build/flight-core-m4',
    'PUBLISHED'
),
(
    'acc_03',
    'Upstream Linux Kernel Socket Probe Patch Accepted',
    '2026-06-05',
    'MILESTONE',
    'Vikram and Dev authored a patch resolving an eBPF socket boundary race condition that was merged directly upstream into linux-stable.',
    'Merged upstream to core Linux',
    'https://github.com/detox-build/net-fuzz',
    'PUBLISHED'
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    date = EXCLUDED.date,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    impact = EXCLUDED.impact,
    verified_link = EXCLUDED.verified_link,
    status = EXCLUDED.status;

-- 6. ANNOUNCEMENTS
INSERT INTO public.announcements (
    id, title, content, type, date, active, status
) VALUES
(
    'ann_01',
    'Lab Oscilloscope Rigol DS1054Z Calibration Complete',
    'Both 4-channel digital storage oscilloscopes in Hardware Lab 2 have been recalibrated and fitted with new 100MHz passive probes. Bench slots open on portal.',
    'INFO',
    '2026-09-15',
    true,
    'PUBLISHED'
),
(
    'ann_02',
    'Paper Salon: FlashAttention-2 Block Tiling Scheduled',
    'Join Meera R. this Thursday at 18:30 IST in Room 204 for line-by-line GPU shared memory arithmetic deconstruction.',
    'RELEASE',
    '2026-09-12',
    true,
    'PUBLISHED'
),
(
    'ann_03',
    'SMD Solder Paste Stencils Arrived from Fabrication',
    'Stainless stencils for flight-core-m4 rev 1.2 have been unpacked. Contact Sneha T. for reflow oven bench access.',
    'INFO',
    '2026-09-08',
    true,
    'PUBLISHED'
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    type = EXCLUDED.type,
    date = EXCLUDED.date,
    active = EXCLUDED.active,
    status = EXCLUDED.status;

-- 7. SUBMISSIONS (Sample Dev Seed)
INSERT INTO public.submissions (
    id, event_id, title, slug, category, description, cover_image, team_name, participant_names, tech_stack, demo_url, repository_url, screenshots, result_badge, published
) VALUES
(
    'sub-orbital-decay',
    'game-building-hackathon-2026',
    'Orbital Decay: N-Body Gravity Slingshot',
    'orbital-decay',
    'Physics Simulation',
    'A real-time N-body gravitational dynamics simulator where players compute orbital transfers, Lagrange points, and gravity assist slingshots to guide stranded interplanetary research probes across chaotic multi-star orbits.',
    'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1200&q=80',
    'Team Kepler-42',
    ARRAY['Dev P.', 'Aditya N.'],
    ARRAY['Rust', 'Bevy', 'Wasm', 'WebGPU', 'Verlet Integration'],
    'https://orbital-decay.detox.build',
    'https://github.com/detox-build/orbital-decay',
    ARRAY['https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80'],
    '1st Place / Overall Winner',
    true
)
ON CONFLICT (id) DO NOTHING;
